### ISSUE TITLE
SQLite caching for event details

### ISSUE THREAD

**Issue by gokulan97** [ShaastraWebops/android-app-2018#12]
The event Schema has been created and now is available in the EventsPortal repository.

The properties that needs to be stored are
Name - event's
vertical 
time
place
contact

Will add more soon. Need to see the schema for myself once.

But start working on this, so that it is a matter of adding new properties.

**Comment by rajatvd** [comment]
Can you give the details of place, contact and time? Do we treat them as raw strings?
