### ISSUE TITLE
Implement Signup and Login for the app

### ISSUE THREAD

**Issue by keer25** [ShaastraWebops/android-app-2018#7]
Gokulan will put up the endpoint soon. Create layout for login and signup. Add a [AsyncTask](https://developer.android.com/reference/android/os/AsyncTask.html) for both the functions.

**Comment by rajatvd** [comment]
Still need the endpoint

**Comment by gokulan97** [comment]
Sorry got busy for sometime. Use CA Portal endpoints as of now. We will change it later.

**Comment by rajatvd** [comment]
Is a server running online?

**Comment by gokulan97** [comment]
Yeah `http://shaastra.org:8080`

**Comment by rajatvd** [comment]
Are there any docs/repo where I can see the endpoint specifics?

**Comment by gokulan97** [comment]
[https://github.com/ShaastraWebops/CA-Site-2018/tree/master/server/api/user](https://github.com/ShaastraWebops/CA-Site-2018/tree/master/server/api/user) This is the folder which contains the code.

For eg, getting details of current user will be `http://shaastra.org:8080/api/users/me`.

**Comment by rajatvd** [comment]
Ok, thanks.

**Comment by gokulan97** [comment]
The EventsPortal will be up soon. Not completed but login and signup endpoints will work. the url will be 
shaastra.org:8000. There is a plan on migration to https. In that case will let you know.

Will give you the wireframes, just need to modify the UI. Hope you are free as this is only the first week. Else somehow make yourself free for the next couple of days. if not, let me know.

**Comment by rajatvd** [comment]
Yes, I can be free for some of the days this week.

**Comment by gokulan97** [comment]
Hope you got the wireframes in the mail @rajatvd .

Screen1 is the splash screen and takes you to screen 2(when the user is not logged in).

From screen 2, on clicking Sign up,  goes to screen 3 and signs in the user and goes to screen 4(which is also a splash screen), after which it goes to the homepage.

Clicking Sign in also opens a sign in page, similar to sign up page. signs you in and takes you to homepage(**NO Screen 4**).

**Comment by gokulan97** [comment]
@avinashselvam can you comment the color-codes which will be helpful for rajat.

**Comment by gokulan97** [comment]
The eventsportal will permanently run at `shaastra.org:8000` permanently. Use the login and signup API and complete the entire module.

**Comment by avinashselvam** [comment]
#004e92, #000428

**Comment by rajatvd** [comment]
The first splash screen is purely for branding purposes right? And the second one(screen 4) is for loading time?

**Comment by vikranth1997** [comment]
@rajatvd So as i told you have a timer for the firstscreen and then comes the second one (screen 4)...have two activities for both of them and do an intent with a timer....and then comes the register or login screens

**Comment by rajatvd** [comment]
Can you link the repos you mentioned?

**Comment by vikranth1997** [comment]
[This](https://github.com/ShaastraWebops/android-app-2017) is the last yr app repo

**Comment by gokulan97** [comment]
If this is done, close the issue.

**Comment by rajatvd** [comment]
I have to add the endpoints still

**Comment by gokulan97** [comment]
The status of this?

**Comment by rajatvd** [comment]
Will finish by today

**Comment by gokulan97** [comment]
The questions have been sent. Please do the needful :)
