### ISSUE TITLE
Navigation drawer

### ISSUE THREAD

**Issue by vikranth1997** [ShaastraWebops/android-app-2018#9]
@Rohithram create a navigation drawer activity and then create fragments : 

1 Home
--division--

1 User Profile
2 Logout

--division--  (if ur not geting what is a division just see the gmail app how it is dividing content on nav bar)

(name this division as Shaastra)
1 Events
2 Workshops
3 Shows
4 Summit
5 Spotlight
6 Hospitality
7 Map

--division--
(name as others)
QR Scanner

so now have the QR Scanner fragment that u've done before in here (i mean to say when u click the QR scanner it should open the fragment that u've done before) and also similarily for the Map thing that u've completed before. Have evrything on the nav bar opening to a fragments 

Acknowledge the issue...if therez any problem comment over here

**Comment by vikranth1997** [comment]
So all the fragments which u create will be worked once the total plan is ready so for now just create the basic navigational layout and for now make sure the maps and qr scanner are working.....is therez any doubt clone the last year repo and have a look at it

**Comment by Rohithram** [comment]
ok

**Comment by gokulan97** [comment]
Complete this by today positively.

**Comment by gokulan97** [comment]
@vikranth1997 has missed sponsors in it.

The complete list would be

1 Home
2 User Profile

1 Events
2 Workshops
3 Summit
4 Spotlight
5 Shows
6 Hospitality
7 Map
8 Sponsors

1 QR Scanner
2 Logout

The order is based on the usage of each menu item
Will comment if there are any additions to this.

**Comment by Rohithram** [comment]
ok

**Comment by Rohithram** [comment]
Nav drawer almost done , tell if any changes required

**Comment by gokulan97** [comment]
Closed as completed
